### ISSUE TITLE
Typo in yum output

### ISSUE THREAD

**Issue by tsbarnes** [clieg/cfetch#18]
The number of yum packages display is missing a closing parentheses.

For example, on my system it looks like this:

```
PKGS   2546 (dnf), 81 (flatpak), 2563 (rpm), 2545 (yum
```

Notice the missing `)` after "yum"

Looking at the source code, it looks like yay has the same typo.

**Comment by clieg** [comment]
Hello, I have now fixed the typo, thank you for pointing it out :))
